require(clusterProfiler)library(rat2302.db)
library(org.Rn.eg.db)keytypes(org.Rn.eg.db)
setwd("/Users/lindadib/Work/SIB-BCF/work/SIB_tutoring/Dib_EA/2019/dataExerciceExtra")#USE RAT DATABASES AND ANNOTATIONrat<-read.csv("rat_KD.txt", sep = "\t", header = T, stringsAsFactors=FALSE) 
PROBES <- rat$row.names

OUT    <- select(rat2302.db,keys= PROBES, columns=c("SYMBOL", "ENTREZID", "ENSEMBL"))duplicated(OUT$PROBEID)OUT    <-OUT[-which(duplicated(OUT$PROBEID)),]dim(OUT)

ttestRat <- function(df, grp1, grp2){x = df[grp1];y = df[grp2];x = as.numeric(x);y = as.numeric(y);results = t.test(x,y);
results$p.value;}rawp <- apply(rat, 1, ttestRat, grp1 = c(2:7), grp2 = c(8:12))names(rawp)	<-OUT$ENSEMBLsortedrawp	<-sort(rawp)p_holm 		<-p.adjust(sortedrawp,method="BH") names(p_holm)	<-names(sortedrawp)SCORE		<-p_holm SCORE		<-sort(SCORE, decreasing=TRUE) head(SCORE) egoGSECC <- gseGO(geneList= SCORE,              OrgDb        = org.Rn.eg.db,              keyType      = 'ENSEMBL',              ont          = "CC",              nPerm        = 1000,              minGSSize    = 10,              maxGSSize    = 500,              pvalueCutoff = 1,              verbose      = FALSE)head(egoGSECC)gseaplot(egoGSECC , geneSetID="GO:0014069")dotplot(egoGSECC , showCategory=30)enrichMap(egoGSECC )plotGOgraph(egoGSECC )# KEGG ONLY WORKS WITH ENTREZ IDrawp <- apply(rat, 1, ttestRat, grp1 = c(2:7), grp2 = c(8:12))names(rawp)	<-OUT$ENTREZsortedrawp	<-sort(rawp)p_holm 		<-p.adjust(sortedrawp,method="BH") names(p_holm)	<-names(sortedrawp)SCORE		<-p_holm SCORE		<-sort(SCORE, decreasing=TRUE) head(SCORE) kk2 <- gseKEGG(geneList    = SCORE,	     organism     = 'rat',               nPerm        = 1000,               minGSSize    = 10,               pvalueCutoff = 1,               verbose      = FALSE)head(kk2)###library(gtools)fcRat <- function(df, grp1, grp2) {x = df[grp1];y = df[grp2];x = as.numeric(x); y = as.numeric(y);x = mean(x);y = mean(y);foldchange(x, y);}
rawp 	<- apply(rat, 1, ttestRat, grp1 = c(2:7), grp2 = c(8:12))Fc	<- apply(rat, 1, fcRat   , grp1 = c(2:7), grp2 = c(8:12))resExp		     <- data.frame(pValues=rawp, log2FC=Fc, name=OUT$ENSEMBL)topDEGenesDetails    <- resExp[which(resExp[,1] < 0.01 & abs(resExp[,2])>2), ]topDEGenesFC         <- resExp[which(resExp[,1] < 0.01 & abs(resExp[,2])>2),3]mydf <- data.frame(ENSEMBL=topDEGenesFC, FC=topDEGenesDetails[,2])mydf$group 		 <- "upregulated"mydf$group[mydf$FC < 0]  <- "downregulated"formula_res <- compareCluster(ENSEMBL~group,                data		= mydf,                fun		= "enrichGO",               keyType       	= 'ENSEMBL',               OrgDb  	= org.Rn.eg.db,               ont           	= "ALL",               pAdjustMethod 	= "BH",               pvalueCutoff  	= 0.01,               qvalueCutoff  	= 0.05,               readable      	= TRUE)dotplot(formula_res,font.size=10)